### ISSUE TITLE
Why isn't Clojush updated?

### ISSUE THREAD

**Issue by saulshanabrook** [fbellomi/crossclj#11]
How can I get CrossClj to build a newer version of [Clojush](https://github.com/lspector/Clojush)? The [current one](https://crossclj.info/ns/clojush/20110702-kephale.17/project.clj.html) is multiple years old and it has had many releases since then on Clojars.

**Comment by fbellomi** [comment]
Hi Saul,

I suspect that the issue is caused by the fact that all version tags are parsed using Aether's GenerifVersionScheme#parseVersion and compared using Aether's GenericVersion#compareTo

http://grepcode.com/file/repo1.maven.org/maven2/org.sonatype.aether/aether-util/1.11/org/sonatype/aether/util/version/GenericVersion.java#GenericVersion.compareTo%28org.sonatype.aether.version.Version%29

Here is a test:

(def version-scheme (GenericVersionScheme.))

(defn compare-ver [a b] 
  (.compareTo (.parseVersion version-scheme a) (.parseVersion version-scheme b)))

(compare-ver "1.2.3" "1.2.1")
=> 1

(compare-ver "20110702-kephale.17" "2.0.53")
=> 1

So your older version is "higher" by Maven's standard. 
I don't know if there are better libraries around to compare versions, any suggestions?

thanks,
Francesco

**Comment by saulshanabrook** [comment]
Interesting. I don't think the solution is to try to get a "better" version comparison, because comparing two versions of different formats seems too hard.

Is there any way to use the date of the release instead of just the version number?

**Comment by fbellomi** [comment]
I see your point, however it seems that the versioning scheme for Maven artifacts (which is the basis for Leiningen/Clojars artifact versioning) is well defined

https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855

http://semver.org/spec/v2.0.0.html

so I believe there is value in sticking to it.

Clojars seems to give more prominence to the time of publishing, and this makes sense because they are keeping all versions.
CrossClj chooses to keep the "highest" release (it has not the resources to host everything), which is not generally the same as the last published one (one could publish 1.1 after 2.0 after 1.0)

**Comment by saulshanabrook** [comment]
So is there anyway to get get it to use the most recent version of Clojush?
