### ISSUE TITLE
Typed Clojure

### ISSUE THREAD

**Issue by saulshanabrook** [fbellomi/crossclj#12]
Does this support adding the types from `core.typed` automatically to the generated documentation?

**Comment by fbellomi** [comment]
Hi Saul,

I experimented with supporting Typed Clojure in CrossClj last year; however I removed the support some months ago, mainly because the usage is very very limited, and the TC toolchain integration within CrossClj was not optimal/easy;
TC is evolved in the last year, and maybe I will consider supporting it in the future.

thanks, Francesco

**Comment by saulshanabrook** [comment]
@fbellomi Cool, that makes sense. Yeah I was looking into using Typed Clojure for a library I am working on, but it seems really unclear how to best do that, at this point, since the tooling around it doesn't exist yet.
